services:

  emqx:
    image: emqx/emqx:5.10.2
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "18083:18083"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log

  nodered:
    image: nodered/node-red:4.1.1-22
    container_name: nodered
    depends_on:
      - emqx
    restart: unless-stopped
    ports:
      - "1880:1880"
      - "1884:1884"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./nodered/data:/data
      - ./data:/data/share

  rmlmapper:
    build: ./rml
    container_name: rmlmapper
    depends_on:
      - nodered
      - graphdb
    restart: unless-stopped
    entrypoint: ["/bin/sh","/work/run.sh"]
    ports:
      - "8080:8080"
    volumes:

      - ./rml/run.sh:/work/run.sh:ro
      - ./rml/trigger_server.py:/work/trigger_server.py:ro
      - ./rml/map_and_post.sh:/work/map_and_post.sh:ro
      - ./rml/control-packets:/work/control-packets:ro
      - ./data:/work/data

  graphdb:
    image: ontotext/graphdb:10.8.11
    container_name: graphdb
    restart: unless-stopped
    ports:
      - "7200:7200"
    environment:
      - GDB_HEAP_SIZE=2g
    volumes:
      - graphdb-data:/opt/graphdb/home

  jupyter:
    build: ./jupyter
    container_name: jupyter
    restart: unless-stopped
    depends_on:
      - graphdb
    ports:
      - "8888:8888"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./jupyter/notebooks:/work/notebooks 

volumes:
  graphdb-data:
